### ISSUE TITLE
阿巴阿巴，大佬，阿巴阿巴。 passwall修复了吗？

### ISSUE THREAD

**Issue by yhxaxy** [DHDAXCW/NanoPi-R2S-2021#14]
阿巴阿巴，大佬，阿巴阿巴。 passwall修复了吗？ 我26用起来还是坏的 27修复了吗？ 就是很神奇 我如果没用passwall前进入b站 然后开启了passwall 然后再开个b站就打不开 但是之前的那个可以正常的观看视频 直播 和打开动态什么的 但如果刷新一下就凉凉

**Comment by DHDAXCW** [comment]
你找原作者。
