### ISSUE TITLE
AdGuard Home SSRplus

### ISSUE THREAD

**Issue by cht6688** [DHDAXCW/NanoPi-R2S-2021#2]
rt 
点击启用后显示error!bin path is a dir

ssrplus打开gfw模式后无法正常链接google等网站，但使用状态内的【谷歌】连通性检查 是连通的
切换为绕过中国大陆ip后正常链接

**Comment by DHDAXCW** [comment]
OK, I'll fix it

**Comment by yikexiaoyao** [comment]
大佬，请问为什么更新系统之后AdGuard Home启动不了，一直显示未运行，打上勾保存并应用也是这样，之前一直好好的，今天更新刚碰到这个问题，而且刷了几次系统都这样

**Comment by DHDAXCW** [comment]
这个问题确实有类似，今晚准备修复，明天18版就可以用上了。三天我好久没弄r2s  而精力都在r4s上，正好今天r4s稳了，可以继续搞r2s。绝对不会让你们失望

**Comment by yikexiaoyao** [comment]
非常感谢⋪(●ൠ●)⋫و牛年快乐✧ tianyu chen 邮箱：ctychentianyu1999@gmail.com 签名由 网易邮箱大师 定制 On 02/17/2021 21:14, 骷髅头 wrote: 这个问题确实有类似，今晚准备修复，明天18版就可以用上了。三天我好久没弄r2s 而精力都在r4s上，正好今天r4s稳了，可以继续搞r2s。绝对不会让你们失望 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yikexiaoyao** [comment]
顺便问一句，回头我是应该直接升级还是重新刷系统呢？

**Comment by DHDAXCW** [comment]
当然是卡刷。不过你可以直接升级也行。但是不保证系统稳定性

**Comment by yikexiaoyao** [comment]
OK

**Comment by yikexiaoyao** [comment]
为什么18号上午发布的固件突然删掉了，后来晚上又重新发布了呢？

**Comment by DHDAXCW** [comment]
因为固件挑卡问题，所以删除，先解决挑卡问题再编译重新发布，这就是最好的
