### ISSUE TITLE
这个版本的无线没有了？

### ISSUE THREAD

**Issue by gLoCk27** [DHDAXCW/NanoPi-R2S-2021#36]
如题，旧版(2021.03.12)是有无线的。

主机名 | OpenWrt
-- | --
型号 | FriendlyElec NanoPi R2S
架构 | ARMv8 Processor rev 4 (v8l) x 4 (1008MHz, 45.5°C)
固件版本 | OpenWrt R21.2.1 (2021.03.23) / LuCI Master (git-21.035.34289-13f96d1)
内核版本 | 5.4.105

**Comment by boregodie** [comment]
同问

**Comment by microyin715** [comment]
同问

**Comment by limpo** [comment]
> 同问

无线很有用吗？速度应该没有硬路由的好吧

**Comment by rovdlx** [comment]
3.28的也还是没有

**Comment by DHDAXCW** [comment]
> 3.28的也还是没有
> 

说下型号，我去查查

**Comment by rovdlx** [comment]
> > 3.28的也还是没有
> 
> 说下型号，我去查查

RTL8811CU

**Comment by gLoCk27** [comment]
Comfast的cf811ac，芯片是 RTL8821CU

**Comment by DHDAXCW** [comment]
等明天的版本，我从r4s里面拉取驱动吧

**Comment by chuck0400295** [comment]
同问.之前3.18之前的版本有无线信号,

**Comment by DHDAXCW** [comment]
今天的版本已加上了驱动，之前驱动链接已失效了。。。现在可以了。感谢反馈
