### ISSUE TITLE
r2s网口没有互换了，还能跑到900m吗？

### ISSUE THREAD

**Issue by ERRORCODE6** [DHDAXCW/NanoPi-R2S-2021#40]
现在是不是不需要互换就能跑到940m ?  是不是新固件那个usb3.0转的网口加了usb3.0的驱动？

**Comment by DHDAXCW** [comment]
上了药引子，不用互换，一样跑满
![image](https://user-images.githubusercontent.com/74764072/140885226-2fe40d44-1177-45bc-bfbe-4134d3248c45.png)

**Comment by DHDAXCW** [comment]
内网iperf3
![image](https://user-images.githubusercontent.com/74764072/140885582-f3c0d661-d60d-473c-bd35-74e93141fccd.png)

**Comment by ERRORCODE6** [comment]
非常给力
