### ISSUE TITLE
风扇一直转。

### ISSUE THREAD

**Issue by comicmanz** [DHDAXCW/NanoPi-R2S-2021#43]
从主页的风扇链接买了B款Fan口供电风扇，装了11.25刚出的全功能版固件，系统启动项中fa-rk3328-pwmfan也在运行，但是风扇还是一直都在转。是否插件还是有问题？望能修复，非常感谢。

**Comment by DHDAXCW** [comment]
如果我移除此脚本，那么风扇不转了。怎么办？

**Comment by lifenots** [comment]
> 这个需要去给这个权限才行

具体怎么设置温控风扇，我也好需要。

**Comment by DHDAXCW** [comment]
有人pr了，等明天看看

**Comment by DHDAXCW** [comment]
已解决
