### ISSUE TITLE
27号之后的版本在releases中无法找到

### ISSUE THREAD

**Issue by YeTianXingShi** [DHDAXCW/NanoPi-R2S-2021#45]
![image](https://user-images.githubusercontent.com/42585691/112951322-cd7e4780-916d-11eb-9c87-8e760c0f5cb8.png)
能够看到的最新的就算27号的版本。但是在issues中看到部分人已经升级到了29版本 而且更新日志也说有28号版本。
因此想问问最新版现在在哪里下载呢？

**Comment by Studenthero** [comment]
作者暂时删除了，因为编译有些问题，等待新的包发布吧。
