### ISSUE TITLE
大佬4月1号版本更新后smartdns插件不见了！

### ISSUE THREAD

**Issue by wei727** [DHDAXCW/NanoPi-R2S-2021#47]
在软件包里面显示又安装了，但是服务里面找不到。。。
Package smartdns (1.2020.09.08-2235-1) installed in root is up to date.

**Comment by DHDAXCW** [comment]
这日志显示编译已上去了。卡刷的？重启一下
![mmexport1617265842209.png](https://user-images.githubusercontent.com/74764072/113266447-de62c080-9307-11eb-8c18-b3a2ec216aae.png)

**Comment by wei727** [comment]
> 这日志显示编译已上去了。卡刷的？重启一下
> ![mmexport1617265842209.png](https://user-images.githubusercontent.com/74764072/113266447-de62c080-9307-11eb-8c18-b3a2ec216aae.png)

不是卡刷用系统升级的，已经重启过了服务里面不显示。我已经回滚3月27号版本了。

**Comment by DHDAXCW** [comment]
> > 这日志显示编译已上去了。卡刷的？重启一下
> > ![mmexport1617265842209.png](https://user-images.githubusercontent.com/74764072/113266447-de62c080-9307-11eb-8c18-b3a2ec216aae.png)
> 
> 不是卡刷用系统升级的，已经重启过了服务里面不显示。我已经回滚3月27号版本了。

我刚才试了，我的有显示的，r2s和r4s也试了，都有的。建议卡刷。我用的卡是三星，不管怎么折腾都好好的。

**Comment by wei727** [comment]
> > > 这日志显示编译已上去了。卡刷的？重启一下
> > > ![mmexport1617265842209.png](https://user-images.githubusercontent.com/74764072/113266447-de62c080-9307-11eb-8c18-b3a2ec216aae.png)
> > 
> > 
> > 不是卡刷用系统升级的，已经重启过了服务里面不显示。我已经回滚3月27号版本了。
> 
> 我刚才试了，我的有显示的，r2s和r4s也试了，都有的。建议卡刷。

好的，谢谢大佬。我系统升级两次失败，把压缩包解压后才升级成功。晚点我卡刷试试！

**Comment by DHDAXCW** [comment]
> > > > 这日志显示编译已上去了。卡刷的？重启一下
> > > > ![mmexport1617265842209.png](https://user-images.githubusercontent.com/74764072/113266447-de62c080-9307-11eb-8c18-b3a2ec216aae.png)
> > > 
> > > 
> > > 不是卡刷用系统升级的，已经重启过了服务里面不显示。我已经回滚3月27号版本了。
> > 
> > 我刚才试了，我的有显示的，r2s和r4s也试了，都有的。建议卡刷。
> 
> 好的，谢谢大佬。我系统升级两次失败，把压缩包解压后才升级成功。晚点我卡刷试试！

已确认了链接有问题，明天就可以用上，今天修改。今晚不要刷了

**Comment by DHDAXCW** [comment]
已修复了，下个版本就有。感谢反馈，我当时不知道这个链接是有问题的。不好意思哈
