### ISSUE TITLE
再反应个插件小问题，AdGuard Home规则丢失！

### ISSUE THREAD

**Issue by wei727** [DHDAXCW/NanoPi-R2S-2021#52]
AdGuard Home每次断电或者重启都会丢失规则文件，哪怕我勾选了备份配置文件还是无法恢复。
![YY截图20210402144937](https://user-images.githubusercontent.com/81148177/113390108-acaf2f80-93c3-11eb-9edb-656433ff242b.jpg)
![规则](https://user-images.githubusercontent.com/81148177/113390224-e122eb80-93c3-11eb-8a3e-384c6bf6d688.jpg)

软件默认保存备份文件路径提示错误，我自己修改了文件备份路径才能正常保存。但是每次断电或者重启后无法恢复！
![YY截图20210402145025](https://user-images.githubusercontent.com/81148177/113390200-d5372980-93c3-11eb-94b4-c3ee66071174.jpg)
![YY截图20210402145046](https://user-images.githubusercontent.com/81148177/113390205-d8321a00-93c3-11eb-8a2f-9f8d4eded1a8.png)

**Comment by DHDAXCW** [comment]
这个一直都是这样的，没办法。

**Comment by DHDAXCW** [comment]
可以这样设置
![mmexport1617347305750.png](https://user-images.githubusercontent.com/74764072/113390966-517e3c80-93c5-11eb-83eb-da3c10cf5193.png)

**Comment by wei727** [comment]
> 可以这样设置
> ![mmexport1617347305750.png](https://user-images.githubusercontent.com/74764072/113390966-517e3c80-93c5-11eb-83eb-da3c10cf5193.png)

好的，谢谢。我马上试试！
