### ISSUE TITLE
大佬停更，不争气的我决定打赏一下！不能白嫖了

### ISSUE THREAD

**Issue by big9588** [DHDAXCW/NanoPi-R2S-2021#59]

**Comment by limpo** [comment]
大家众筹电脑

**Comment by big9588** [comment]
> 大家众筹电脑



> 大家众筹电脑

+1

**Comment by DHDAXCW** [comment]
感谢大家。明天版本，我修复关机异常，后台崩溃。就这两个

**Comment by wei727** [comment]
希望不是永久停更~

**Comment by limpo** [comment]
> 感谢大家。明天版本，我修复关机异常，后台崩溃。就这两个

2021.04.08 WAN/LAN互换 Lean OpenWrt暂停一个月
这个是4.9更新的版本吗？

**Comment by wei727** [comment]
> > 感谢大家。明天版本，我修复关机异常，后台崩溃。就这两个
> 
> 2021.04.08 WAN/LAN互换 Lean OpenWrt暂停一个月
> 这个是4.9更新的版本吗？

不是，你没看这是4月8号的吗！4.9要等明天出来，每天才是最后一个版本。

**Comment by 1017737237** [comment]
+1

**Comment by thomaswcy** [comment]
目前互换固件已经重启了
