### ISSUE TITLE
请问稳定精简版能增加zerotier吗？

### ISSUE THREAD

**Issue by yikexiaoyao** [DHDAXCW/NanoPi-R2S-2021#6]
请问稳定精简版能增加zerotier吗？我在可用软件包里进行了安装，但是没看到在哪里可以使用，能帮忙解决一下吗？非常感谢

**Comment by gLoCk27** [comment]
自从build 2021.05.30之后，各种出问题，aliddns也没有了，最新6.24的京东签到貌似变成了旧版本而且是不能正常用的。
所以一直留着build 2021.05.30不敢升级
