### ISSUE TITLE
发现3.27和4.3最稳定

### ISSUE THREAD

**Issue by seal-net** [DHDAXCW/NanoPi-R2S-2021#62]
都超过一周没死机，有cup调节的800-1.2G，用ssrp+和ddns，其他都关掉。。

**Comment by wei727** [comment]
我停留在4.5了用着也没问题，没死机、没断网、没后台崩溃cup调节的800-1.5G，看着4.8有问题没升级，我这CPU1.6都超过的稳定得很。还有就是cup调节不要低于800不然会出现各种奇怪的问题！

**Comment by VwEl** [comment]
我还在用04.04，可惜上限没开放到1.6G

**Comment by VwEl** [comment]
> 
> 
> 我停留在4.5了用着也没问题，没死机、没断网、没后台崩溃cup调节的800-1.5G，看着4.8有问题没升级，我这CPU1.6都超过的稳定得很。还有就是cup调节不要低于800不然会出现各种奇怪的问题！
我最低408用了一周没问题
