### ISSUE TITLE
请问如何自己安装多线多拨和高级设置这2个插件？

### ISSUE THREAD

**Issue by str0078** [DHDAXCW/NanoPi-R2S-2021#63]
syncdial  #多拨虚拟网卡
使用macvlan驱动创建多个虚拟WAN口，支持并发多拨

advancedsetting  #系统高级设置
可以直接手动编辑网络、防火墙等配置文档

这2个插件在软件包里面没有找到，请问如何自己安装？

**Comment by protectedMan** [comment]
同问

**Comment by protectedMan** [comment]
https://www.getce.cn/show/110.html 发现这个教程, 设置完后重启下多线多拨功能就有了
