### ISSUE TITLE
如何安装jellyfin

### ISSUE THREAD

**Issue by v201314** [DHDAXCW/NanoPi-R2S-2021#65]
请问一下
看更新日志 3.28有
解禁R2S的GPU
添加了 R2S/R4S 的硬件转码，可以用 Jellyfin， 1080p HEVC 10bit 60fps 无需 CPU 参与。
现在用4.11的版本应该怎么才能安装Jellyfin

**Comment by thomaswcy** [comment]
你说r2s跑得动么
