### ISSUE TITLE
R2S TYPE-C  版本中lan口无法识别

### ISSUE THREAD

**Issue by DONGYUSEN** [DHDAXCW/NanoPi-R2S-2021#67]
R2S TYPE-C 109和110版本 都启动不了， 新的110版本只启动出一次 刷王TF卡 重启后 红灯跳
R2S Micro USB的完全可以 同样的32GBTF卡

**Comment by DHDAXCW** [comment]
首先我没有更新内核110🌚🌚
```
木有笔记本电脑...
```
最好选择三星TF卡，随便折腾都好好的
