### ISSUE TITLE
断网

### ISSUE THREAD

**Issue by memkor** [DHDAXCW/NanoPi-R2S-2021#71]
你好 我刷的是你的4月9号固件 使用期间断网设备死机 日志如下，请问是什么问题呢
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:10 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:10 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)

**Comment by memkor** [comment]
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:08 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:09 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)
Tue Apr 13 21:39:10 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to 0.0.0.0:80 failed (98: Address in use)
Tue Apr 13 21:39:10 2021 daemon.err nginx[10849]: 2021/04/13 21:39:08 [emerg] 10849#0: bind() to [::]:80 failed (98: Address in use)

**Comment by xiaoxiao0379** [comment]
cpu调节

**Comment by dev4u** [comment]
刷最近编译的版本可以解决。
