### ISSUE TITLE
您好，型号为rtl8812bu的USB无线网卡驱动能添加进去R2S吗？(华硕USB-AC57）

### ISSUE THREAD

**Issue by yangwen9** [DHDAXCW/NanoPi-R2S-2021#72]
您好，型号为rtl8812bu的USB无线网卡驱动能添加进去R2S吗？(华硕USB-AC57）下面是大神提供的驱动链接，但是本人不会编译进R2S, https://www.github.com/immortalwrt/immortalwrt/tree/master/package/kernel/rtl88x2bu

**Comment by DHDAXCW** [comment]
下个版本加上👌🏻

**Comment by DHDAXCW** [comment]
我刚看了我固件里配置，有这个驱动，可以直接用

**Comment by yangwen9** [comment]
谢谢，我刷最新的固件后试试能否兼容和正常驱动
