### ISSUE TITLE
大神可否加入一键升级功能，定时升级功能

### ISSUE THREAD

**Issue by clincy123** [DHDAXCW/NanoPi-R2S-2021#8]
不懂开发，提个建议。每次都要手动下载比较麻烦。感谢。

**Comment by Minecraftft** [comment]
附议

**Comment by DHDAXCW** [comment]
这个一键升级，我只能用命令升级。我以后会考虑这个问题，先把固件稳定了再说

**Comment by clincy123** [comment]
> 这个一键升级，我只能用命令升级。我以后会考虑这个问题，先把固件稳定了再说



> 这个一键升级，我只能用命令升级。我以后会考虑这个问题，先把固件稳定了再说

**Comment by clincy123** [comment]
> 这个一键升级，我只能用命令升级。我以后会考虑这个问题，先把固件稳定了再说

辛苦大佬
