### ISSUE TITLE
快点更新！

### ISSUE THREAD

**Issue by yhxaxy** [DHDAXCW/NanoPi-R2S-2021#88]
还要几天才更新呀？不是说有个重大更新吗？ 快点啊 等不及了

**Comment by DHDAXCW** [comment]
哈哈，少安毋躁....我今天看了编译，应该快了

**Comment by DHDAXCW** [comment]
再过3小时看看能不能出包

**Comment by seal-net** [comment]
现在的伸手党真无耻

**Comment by thomaswcy** [comment]
给你们固件已经很好了，我们没有义务编译，我们几个开发者完全是在用爱发电，而这些伸手党弄得就像这固件是他们付费买的一样。
