### ISSUE TITLE
7zip无法解压

### ISSUE THREAD

**Issue by whwnow** [DHDAXCW/NanoPi-R2S-2021#89]
openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz
的版本用 7izp 解压时提示有效数据外包含额外数据
7zip版本为： 7-Zip 21.01 alpha (2021-03-09)

**Comment by DHDAXCW** [comment]
不用解压，直接刷也行

**Comment by whwnow** [comment]
> 不用解压，直接刷也行

多谢大佬回复

还有个疑问，首刷不是会有个 factory 的包么，没找到，首刷也可以用这个 sysupgrade 的包么？

**Comment by DHDAXCW** [comment]
factory这包不好搞，何况有卡刷的方便拔了重刷，factory这个只给emmc用的吧
Ext4可以挂载，sq只能读不能写，合适不爱折腾的

**Comment by whwnow** [comment]
> factory这包不好搞，何况有卡刷的方便拔了重刷，factory这个只给emmc用的吧
> Ext4可以挂载，sq只能读不能写，合适不爱折腾的

已经用 sysupgrade 成功刷机了，感谢解惑！
