### ISSUE TITLE
大佬!能否安排一下在线更新脚本

### ISSUE THREAD

**Issue by i-never-left-you** [DHDAXCW/NanoPi-R2S-2021#90]
造福追更狗
使用在线更新后对sd卡扩容根分区至最大,方便折腾

**Comment by DHDAXCW** [comment]
> 造福追更狗
> 使用在线更新后对sd卡扩容根分区至最大,方便折腾
> 

以后吧😅

**Comment by i-never-left-you** [comment]
> > 造福追更狗
> > 使用在线更新后对sd卡扩容根分区至最大,方便折腾
> 
> 以后吧😅

好的,做大做强
