### ISSUE TITLE
qq语音无法听到声音

### ISSUE THREAD

**Issue by faxlok** [DHDAXCW/NanoPi-R2S-2021#95]
第一次提问题，如果不太懂规矩。。。

我刷上你的固件之后，手机连上wifi打qq语音的时候，在qq电话界面会出现网络不稳定，我听不到对面一点声音，对面也听不到我的声音。
用klever1988的固件也是，但是他以前没有换immortalwrt的时候，没有出现这种情况。打手机游戏也时不时会卡，没有用软路由的时候没有这种问题，请问一般是什么原因？是挑卡的原因吗？

**Comment by thomaswcy** [comment]
不是挑卡 你换最新固件试试

**Comment by faxlok** [comment]
> 不是挑卡 你换最新固件试试

好，我晚点我试试。原因我好像找到了，我在手机添加一个dns 8.8.8.8就不会有这个问题了

**Comment by faxlok** [comment]
> 不是挑卡 你换最新固件试试

大佬我来反馈啦，刷了最新的固件5.20网口互换的，这几天都没出现打qq电话的问题
